# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/39551/Desktop/ASIC/Whack-a-Mole-GameMachine/game_machine/game_machine.srcs/sources_1/ip/MusicFalse/MusicFalse.xci
# IP: The module: 'MusicFalse' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/ASIC/Whack-a-Mole-GameMachine/game_machine/game_machine.gen/sources_1/ip/MusicFalse/MusicFalse_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MusicFalse'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/39551/Desktop/ASIC/Whack-a-Mole-GameMachine/game_machine/game_machine.srcs/sources_1/ip/MusicFalse/MusicFalse.xci
# IP: The module: 'MusicFalse' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39551/Desktop/ASIC/Whack-a-Mole-GameMachine/game_machine/game_machine.gen/sources_1/ip/MusicFalse/MusicFalse_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MusicFalse'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
